### ISSUE TITLE
(Mac) adb: error: remote object '/sdcard/autojump.png' does not exist

### ISSUE THREAD

**Issue by wwpokenet** [declan94/ssproject_jumper#2]
如题，成功截图后打算pull到本地，报错。
adb shell进去后能看到/sdcard下有autojump.jpg文件。chmod 777 autojump.jpg 无任何提示，但ls -l后依旧没有权限变动：
-rw-rw---- root     sdcard_rw   445226 2018-06-15 02:21 autojump.jpg

**Comment by zhangzw16** [comment]
xx-zhou fixed the bug, it should works fine now.
Can you update the project and see if it works fine? @wwpokenet

**Comment by wwpokenet** [comment]
Another bug occurs：

/sdcard/autojump.png: 1 file pulled. 52.1 MB/s (245125 bytes in 0.004s)
<PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1080x1920 at 0x10B929810>
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    main()
  File "main.py", line 8, in main
    distance = jumper();
  File "/Users/madistia/Downloads/ssproject_jumper-master/src/jump_python/jumper.py", line 35, in jumper
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
NameError: global name 'im' is not defined

I  fixed this bug and launch a new pull requests. However, the baseline method can't work well on my laptop--always jump tooooooo far.

**Comment by wwpokenet** [comment]
Well, on macOS I need to chmod +X /dependency/platform-tools-macos/adb to run the adb.
Maybe you need to tell others in README.

**Comment by zhangzw16** [comment]
you should try to pull the newest version, and try that on your mac.
And thank you for your pr.

**Comment by wwpokenet** [comment]
It works. Good job😃
Btw, the indent of /src/jumper_python/jumper.py is still not inconsistent (both tab and space). Maybe you should try to fix it.
